version: "1.0.0"
metadata:
  name: "sample-deployment"
  environment: "prod"
  description: "Sample E2E Kubernetes deployment"
  tags:
    environment: "production"
    monitoring: "enabled"
  namespace: "sample-app"

registry:
  url: "docker.io"
  type: "dockerhub"
  insecure: false

kubernetes:
  version: "1.28"
  namespace: "sample-app"
  networking: "calico"
  storage: "local-path"
  ingress:
    enabled: true
    class: "nginx"
    tls: true
    certManager: true
  rbac:
    enabled: true

cloud:
  provider: "onprem"
  onprem:
    kubeconfig: "~/.kube/config"
    nodes:
      - "node1.example.com"
      - "node2.example.com"
      - "node3.example.com"

monitoring:
  enabled: true
  prometheus:
    enabled: true
    retention: "15d"
    storage: "10Gi"
  grafana:
    enabled: true
    adminPassword: "admin123"
  alerting:
    enabled: true
    webhookUrl: "https://hooks.slack.com/services/..."

security:
  authentication:
    provider: "oidc"
    settings:
      issuer: "https://auth.example.com"
      clientId: "k8s-installer"
  encryption:
    atRest: true
    inTransit: true
  scanning:
    enabled: true
    vulnScanners:
      - "trivy"
    policyScanners:
      - "gatekeeper"
  policies:
    networkPolicies: true
    podSecurity: true
    rbac: true

application:
  name: "sample-app"
  version: "1.0.0"
  replicas: 3
  image: "nginx:latest"
  port: 80
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  environment:
    NODE_ENV: "production"
    LOG_LEVEL: "info"